# Generated by Django 5.2.6 on 2025-09-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_fix_like_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
